package co.edu.uniautonoma.sioat.datos;
// Generated 6/03/2018 01:23:43 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Activo generated by hbm2java
 */
@Entity
@Table(name = "activo")
public class Activo implements java.io.Serializable {

    private Integer id;
    private String descripcion;
    private int saldoFinal;
    private String notas;
    private Integer ajustes;
    private int renglon33;
    private int renglon34;
    private int renglon35;
    private int renglon36;
    private int renglon37;
    private int renglon38;
    private Set<SubcuentaActivo> subcuentaActivos = new HashSet<SubcuentaActivo>(0);

    public Activo() {
    }

    public Activo(String descripcion, int saldoFinal, int renglon33, int renglon34, int renglon35, int renglon36, int renglon37, int renglon38) {
        this.descripcion = descripcion;
        this.saldoFinal = saldoFinal;
        this.renglon33 = renglon33;
        this.renglon34 = renglon34;
        this.renglon35 = renglon35;
        this.renglon36 = renglon36;
        this.renglon37 = renglon37;
        this.renglon38 = renglon38;
    }

    public Activo(String descripcion, int saldoFinal, String notas, Integer ajustes, int renglon33, int renglon34, int renglon35, int renglon36, int renglon37, int renglon38, Set<SubcuentaActivo> subcuentaActivos) {
        this.descripcion = descripcion;
        this.saldoFinal = saldoFinal;
        this.notas = notas;
        this.ajustes = ajustes;
        this.renglon33 = renglon33;
        this.renglon34 = renglon34;
        this.renglon35 = renglon35;
        this.renglon36 = renglon36;
        this.renglon37 = renglon37;
        this.renglon38 = renglon38;
        this.subcuentaActivos = subcuentaActivos;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "descripcion", nullable = false, length = 45)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Column(name = "saldo_final", nullable = false)
    public int getSaldoFinal() {
        return this.saldoFinal;
    }

    public void setSaldoFinal(int saldoFinal) {
        this.saldoFinal = saldoFinal;
    }

    @Column(name = "notas")
    public String getNotas() {
        return this.notas;
    }

    public void setNotas(String notas) {
        this.notas = notas;
    }

    @Column(name = "ajustes")
    public Integer getAjustes() {
        return this.ajustes;
    }

    public void setAjustes(Integer ajustes) {
        this.ajustes = ajustes;
    }

    @Column(name = "renglon33", nullable = false)
    public int getRenglon33() {
        return this.renglon33;
    }

    public void setRenglon33(int renglon33) {
        this.renglon33 = renglon33;
    }

    @Column(name = "renglon34", nullable = false)
    public int getRenglon34() {
        return this.renglon34;
    }

    public void setRenglon34(int renglon34) {
        this.renglon34 = renglon34;
    }

    @Column(name = "renglon35", nullable = false)
    public int getRenglon35() {
        return this.renglon35;
    }

    public void setRenglon35(int renglon35) {
        this.renglon35 = renglon35;
    }

    @Column(name = "renglon36", nullable = false)
    public int getRenglon36() {
        return this.renglon36;
    }

    public void setRenglon36(int renglon36) {
        this.renglon36 = renglon36;
    }

    @Column(name = "renglon37", nullable = false)
    public int getRenglon37() {
        return this.renglon37;
    }

    public void setRenglon37(int renglon37) {
        this.renglon37 = renglon37;
    }

    @Column(name = "renglon38", nullable = false)
    public int getRenglon38() {
        return this.renglon38;
    }

    public void setRenglon38(int renglon38) {
        this.renglon38 = renglon38;
    }

    @XmlTransient
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "activo")
    public Set<SubcuentaActivo> getSubcuentaActivos() {
        return this.subcuentaActivos;
    }

    public void setSubcuentaActivos(Set<SubcuentaActivo> subcuentaActivos) {
        this.subcuentaActivos = subcuentaActivos;
    }

}
