package co.edu.uniautonoma.sioat.datos;
// Generated 6/03/2018 01:23:43 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "cliente")
public class Cliente implements java.io.Serializable {

    private Integer id;
    private CodigoAdministracion codigoAdministracion;
    private SubActividadEconomica subActividadEconomica;
    private TipoContribuyente tipoContribuyente;
    private TipoResponsabilidad tipoResponsabilidad;
    private Usuario usuario;
    private String nombre;
    private int nit;
    private String apellido;
    private int digitoVerificacion;
    private Character tcp;
    private String razonSocial;
    private String nitFirmantel;
    private int numeroTarjetaRevisor;
    private String codDireccionSeccional;
    private String codigoCorrecion;
    private String formularioAnterior;
    private Integer digitoVerificacionFirmante;
    private Boolean habilitado;
    private Set<Renta> rentas = new HashSet<Renta>(0);

    public Cliente() {
    }

    public Cliente(CodigoAdministracion codigoAdministracion, SubActividadEconomica subActividadEconomica, TipoContribuyente tipoContribuyente, TipoResponsabilidad tipoResponsabilidad, Usuario usuario, String nombre, int nit, String apellido, int digitoVerificacion, String razonSocial, String nitFirmantel, int numeroTarjetaRevisor, String codDireccionSeccional) {
        this.codigoAdministracion = codigoAdministracion;
        this.subActividadEconomica = subActividadEconomica;
        this.tipoContribuyente = tipoContribuyente;
        this.tipoResponsabilidad = tipoResponsabilidad;
        this.usuario = usuario;
        this.nombre = nombre;
        this.nit = nit;
        this.apellido = apellido;
        this.digitoVerificacion = digitoVerificacion;
        this.razonSocial = razonSocial;
        this.nitFirmantel = nitFirmantel;
        this.numeroTarjetaRevisor = numeroTarjetaRevisor;
        this.codDireccionSeccional = codDireccionSeccional;
    }

    public Cliente(CodigoAdministracion codigoAdministracion, SubActividadEconomica subActividadEconomica, TipoContribuyente tipoContribuyente, TipoResponsabilidad tipoResponsabilidad, Usuario usuario, String nombre, int nit, String apellido, int digitoVerificacion, Character tcp, String razonSocial, String nitFirmantel, int numeroTarjetaRevisor, String codDireccionSeccional, String codigoCorrecion, String formularioAnterior, Integer digitoVerificacionFirmante, Boolean habilitado, Set<Renta> rentas) {
        this.codigoAdministracion = codigoAdministracion;
        this.subActividadEconomica = subActividadEconomica;
        this.tipoContribuyente = tipoContribuyente;
        this.tipoResponsabilidad = tipoResponsabilidad;
        this.usuario = usuario;
        this.nombre = nombre;
        this.nit = nit;
        this.apellido = apellido;
        this.digitoVerificacion = digitoVerificacion;
        this.tcp = tcp;
        this.razonSocial = razonSocial;
        this.nitFirmantel = nitFirmantel;
        this.numeroTarjetaRevisor = numeroTarjetaRevisor;
        this.codDireccionSeccional = codDireccionSeccional;
        this.codigoCorrecion = codigoCorrecion;
        this.formularioAnterior = formularioAnterior;
        this.digitoVerificacionFirmante = digitoVerificacionFirmante;
        this.habilitado = habilitado;
        this.rentas = rentas;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_codigo_administracion", nullable = false)
    public CodigoAdministracion getCodigoAdministracion() {
        return this.codigoAdministracion;
    }

    public void setCodigoAdministracion(CodigoAdministracion codigoAdministracion) {
        this.codigoAdministracion = codigoAdministracion;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_actividad_economica", nullable = false)
    public SubActividadEconomica getSubActividadEconomica() {
        return this.subActividadEconomica;
    }

    public void setSubActividadEconomica(SubActividadEconomica subActividadEconomica) {
        this.subActividadEconomica = subActividadEconomica;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_tipo_contribuyente", nullable = false)
    public TipoContribuyente getTipoContribuyente() {
        return this.tipoContribuyente;
    }

    public void setTipoContribuyente(TipoContribuyente tipoContribuyente) {
        this.tipoContribuyente = tipoContribuyente;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_tipo_responsabilidad", nullable = false)
    public TipoResponsabilidad getTipoResponsabilidad() {
        return this.tipoResponsabilidad;
    }

    public void setTipoResponsabilidad(TipoResponsabilidad tipoResponsabilidad) {
        this.tipoResponsabilidad = tipoResponsabilidad;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_usuario", nullable = false)
    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @Column(name = "nombre", nullable = false, length = 45)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "nit", nullable = false)
    public int getNit() {
        return this.nit;
    }

    public void setNit(int nit) {
        this.nit = nit;
    }

    @Column(name = "apellido", nullable = false, length = 45)
    public String getApellido() {
        return this.apellido;
    }

    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    @Column(name = "digito_verificacion", nullable = false)
    public int getDigitoVerificacion() {
        return this.digitoVerificacion;
    }

    public void setDigitoVerificacion(int digitoVerificacion) {
        this.digitoVerificacion = digitoVerificacion;
    }

    @Column(name = "tcp", length = 1)
    public Character getTcp() {
        return this.tcp;
    }

    public void setTcp(Character tcp) {
        this.tcp = tcp;
    }

    @Column(name = "razon_social", nullable = false, length = 45)
    public String getRazonSocial() {
        return this.razonSocial;
    }

    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }

    @Column(name = "nit_firmantel", nullable = false, length = 45)
    public String getNitFirmantel() {
        return this.nitFirmantel;
    }

    public void setNitFirmantel(String nitFirmantel) {
        this.nitFirmantel = nitFirmantel;
    }

    @Column(name = "numero_tarjeta_revisor", nullable = false)
    public int getNumeroTarjetaRevisor() {
        return this.numeroTarjetaRevisor;
    }

    public void setNumeroTarjetaRevisor(int numeroTarjetaRevisor) {
        this.numeroTarjetaRevisor = numeroTarjetaRevisor;
    }

    @Column(name = "cod_direccion_seccional", nullable = false, length = 45)
    public String getCodDireccionSeccional() {
        return this.codDireccionSeccional;
    }

    public void setCodDireccionSeccional(String codDireccionSeccional) {
        this.codDireccionSeccional = codDireccionSeccional;
    }

    @Column(name = "codigo_correcion", length = 45)
    public String getCodigoCorrecion() {
        return this.codigoCorrecion;
    }

    public void setCodigoCorrecion(String codigoCorrecion) {
        this.codigoCorrecion = codigoCorrecion;
    }

    @Column(name = "formulario_anterior", length = 45)
    public String getFormularioAnterior() {
        return this.formularioAnterior;
    }

    public void setFormularioAnterior(String formularioAnterior) {
        this.formularioAnterior = formularioAnterior;
    }

    @Column(name = "digito_verificacion_firmante")
    public Integer getDigitoVerificacionFirmante() {
        return this.digitoVerificacionFirmante;
    }

    public void setDigitoVerificacionFirmante(Integer digitoVerificacionFirmante) {
        this.digitoVerificacionFirmante = digitoVerificacionFirmante;
    }

    @Column(name = "habilitado")
    public Boolean isHabilitado() {
        return this.habilitado;
    }

    public void setHabilitado(Boolean habilitado) {
        this.habilitado = habilitado;
    }

    @XmlTransient
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
    public Set<Renta> getRentas() {
        return this.rentas;
    }

    public void setRentas(Set<Renta> rentas) {
        this.rentas = rentas;
    }

}
