package co.edu.uniautonoma.sioat.datos;
// Generated 6/03/2018 01:23:43 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Costo generated by hbm2java
 */
@Entity
@Table(name = "costo")
public class Costo implements java.io.Serializable {

    private Integer id;
    private String descripcion;
    private float saldoFinal;
    private String notas;
    private int ajustes;
    private int renglon49;
    private int renglon50;
    private Set<SubcuentaCosto> subcuentaCostos = new HashSet<SubcuentaCosto>(0);

    public Costo() {
    }

    public Costo(String descripcion, float saldoFinal, int ajustes, int renglon49, int renglon50) {
        this.descripcion = descripcion;
        this.saldoFinal = saldoFinal;
        this.ajustes = ajustes;
        this.renglon49 = renglon49;
        this.renglon50 = renglon50;
    }

    public Costo(String descripcion, float saldoFinal, String notas, int ajustes, int renglon49, int renglon50, Set<SubcuentaCosto> subcuentaCostos) {
        this.descripcion = descripcion;
        this.saldoFinal = saldoFinal;
        this.notas = notas;
        this.ajustes = ajustes;
        this.renglon49 = renglon49;
        this.renglon50 = renglon50;
        this.subcuentaCostos = subcuentaCostos;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "descripcion", nullable = false, length = 45)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Column(name = "saldo_final", nullable = false, precision = 12, scale = 0)
    public float getSaldoFinal() {
        return this.saldoFinal;
    }

    public void setSaldoFinal(float saldoFinal) {
        this.saldoFinal = saldoFinal;
    }

    @Column(name = "notas")
    public String getNotas() {
        return this.notas;
    }

    public void setNotas(String notas) {
        this.notas = notas;
    }

    @Column(name = "ajustes", nullable = false)
    public int getAjustes() {
        return this.ajustes;
    }

    public void setAjustes(int ajustes) {
        this.ajustes = ajustes;
    }

    @Column(name = "renglon49", nullable = false)
    public int getRenglon49() {
        return this.renglon49;
    }

    public void setRenglon49(int renglon49) {
        this.renglon49 = renglon49;
    }

    @Column(name = "renglon50", nullable = false)
    public int getRenglon50() {
        return this.renglon50;
    }

    public void setRenglon50(int renglon50) {
        this.renglon50 = renglon50;
    }

    @XmlTransient
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "costo")
    public Set<SubcuentaCosto> getSubcuentaCostos() {
        return this.subcuentaCostos;
    }

    public void setSubcuentaCostos(Set<SubcuentaCosto> subcuentaCostos) {
        this.subcuentaCostos = subcuentaCostos;
    }

}
