package co.edu.uniautonoma.sioat.datos;
// Generated 6/03/2018 01:23:43 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Ingreso generated by hbm2java
 */
@Entity
@Table(name = "ingreso")
public class Ingreso implements java.io.Serializable {

    private Integer id;
    private String descripcion;
    private float saldoFinal;
    private String notas;
    private Integer ajustes;
    private int renglon42;
    private int renglon43;
    private int renglon44;
    private int renglon46;
    private int renglon47;
    private int idSubcuenta;
    private Set<SubcuentaIngreso> subcuentaIngresos = new HashSet<SubcuentaIngreso>(0);

    public Ingreso() {
    }

    public Ingreso(String descripcion, float saldoFinal, int renglon42, int renglon43, int renglon44, int renglon46, int renglon47, int idSubcuenta) {
        this.descripcion = descripcion;
        this.saldoFinal = saldoFinal;
        this.renglon42 = renglon42;
        this.renglon43 = renglon43;
        this.renglon44 = renglon44;
        this.renglon46 = renglon46;
        this.renglon47 = renglon47;
        this.idSubcuenta = idSubcuenta;
    }

    public Ingreso(String descripcion, float saldoFinal, String notas, Integer ajustes, int renglon42, int renglon43, int renglon44, int renglon46, int renglon47, int idSubcuenta, Set<SubcuentaIngreso> subcuentaIngresos) {
        this.descripcion = descripcion;
        this.saldoFinal = saldoFinal;
        this.notas = notas;
        this.ajustes = ajustes;
        this.renglon42 = renglon42;
        this.renglon43 = renglon43;
        this.renglon44 = renglon44;
        this.renglon46 = renglon46;
        this.renglon47 = renglon47;
        this.idSubcuenta = idSubcuenta;
        this.subcuentaIngresos = subcuentaIngresos;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "descripcion", nullable = false, length = 45)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Column(name = "saldo_final", nullable = false, precision = 12, scale = 0)
    public float getSaldoFinal() {
        return this.saldoFinal;
    }

    public void setSaldoFinal(float saldoFinal) {
        this.saldoFinal = saldoFinal;
    }

    @Column(name = "notas")
    public String getNotas() {
        return this.notas;
    }

    public void setNotas(String notas) {
        this.notas = notas;
    }

    @Column(name = "ajustes")
    public Integer getAjustes() {
        return this.ajustes;
    }

    public void setAjustes(Integer ajustes) {
        this.ajustes = ajustes;
    }

    @Column(name = "renglon42", nullable = false)
    public int getRenglon42() {
        return this.renglon42;
    }

    public void setRenglon42(int renglon42) {
        this.renglon42 = renglon42;
    }

    @Column(name = "renglon43", nullable = false)
    public int getRenglon43() {
        return this.renglon43;
    }

    public void setRenglon43(int renglon43) {
        this.renglon43 = renglon43;
    }

    @Column(name = "renglon44", nullable = false)
    public int getRenglon44() {
        return this.renglon44;
    }

    public void setRenglon44(int renglon44) {
        this.renglon44 = renglon44;
    }

    @Column(name = "renglon46", nullable = false)
    public int getRenglon46() {
        return this.renglon46;
    }

    public void setRenglon46(int renglon46) {
        this.renglon46 = renglon46;
    }

    @Column(name = "renglon47", nullable = false)
    public int getRenglon47() {
        return this.renglon47;
    }

    public void setRenglon47(int renglon47) {
        this.renglon47 = renglon47;
    }

    @Column(name = "id_subcuenta", nullable = false)
    public int getIdSubcuenta() {
        return this.idSubcuenta;
    }

    public void setIdSubcuenta(int idSubcuenta) {
        this.idSubcuenta = idSubcuenta;
    }

    @XmlTransient
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "ingreso")
    public Set<SubcuentaIngreso> getSubcuentaIngresos() {
        return this.subcuentaIngresos;
    }

    public void setSubcuentaIngresos(Set<SubcuentaIngreso> subcuentaIngresos) {
        this.subcuentaIngresos = subcuentaIngresos;
    }

}
