package co.edu.uniautonoma.sioat.datos;
// Generated 6/03/2018 01:23:43 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Pasivo generated by hbm2java
 */
@Entity
@Table(name = "pasivo")
public class Pasivo implements java.io.Serializable {

    private Integer id;
    private String descripcion;
    private float saldoFinal;
    private String notas;
    private Double ajustes;
    private int renglon40;
    private Set<SubcuentaPasivo> subcuentaPasivos = new HashSet<SubcuentaPasivo>(0);

    public Pasivo() {
    }

    public Pasivo(String descripcion, float saldoFinal, int renglon40) {
        this.descripcion = descripcion;
        this.saldoFinal = saldoFinal;
        this.renglon40 = renglon40;
    }

    public Pasivo(String descripcion, float saldoFinal, String notas, Double ajustes, int renglon40, Set<SubcuentaPasivo> subcuentaPasivos) {
        this.descripcion = descripcion;
        this.saldoFinal = saldoFinal;
        this.notas = notas;
        this.ajustes = ajustes;
        this.renglon40 = renglon40;
        this.subcuentaPasivos = subcuentaPasivos;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "descripcion", nullable = false, length = 45)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Column(name = "saldo_final", nullable = false, precision = 12, scale = 0)
    public float getSaldoFinal() {
        return this.saldoFinal;
    }

    public void setSaldoFinal(float saldoFinal) {
        this.saldoFinal = saldoFinal;
    }

    @Column(name = "notas")
    public String getNotas() {
        return this.notas;
    }

    public void setNotas(String notas) {
        this.notas = notas;
    }

    @Column(name = "ajustes", precision = 22, scale = 0)
    public Double getAjustes() {
        return this.ajustes;
    }

    public void setAjustes(Double ajustes) {
        this.ajustes = ajustes;
    }

    @Column(name = "renglon40", nullable = false)
    public int getRenglon40() {
        return this.renglon40;
    }

    public void setRenglon40(int renglon40) {
        this.renglon40 = renglon40;
    }

    @XmlTransient
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pasivo")
    public Set<SubcuentaPasivo> getSubcuentaPasivos() {
        return this.subcuentaPasivos;
    }

    public void setSubcuentaPasivos(Set<SubcuentaPasivo> subcuentaPasivos) {
        this.subcuentaPasivos = subcuentaPasivos;
    }

}
