package co.edu.uniautonoma.sioat.datos;
// Generated 6/03/2018 01:23:43 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

/**
 * SubActividadEconomica generated by hbm2java
 */
@Entity
@Table(name = "sub_actividad_economica")
public class SubActividadEconomica implements java.io.Serializable {

    private Integer id;
    private ActividadEconomica actividadEconomica;
    private String codigo;
    private String nombre;
    private Set<Cliente> clientes = new HashSet<Cliente>(0);

    public SubActividadEconomica() {
    }

    public SubActividadEconomica(ActividadEconomica actividadEconomica, String codigo, String nombre, Set<Cliente> clientes) {
        this.actividadEconomica = actividadEconomica;
        this.codigo = codigo;
        this.nombre = nombre;
        this.clientes = clientes;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_actividad_economica")
    public ActividadEconomica getActividadEconomica() {
        return this.actividadEconomica;
    }

    public void setActividadEconomica(ActividadEconomica actividadEconomica) {
        this.actividadEconomica = actividadEconomica;
    }

    @Column(name = "codigo", length = 50)
    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    @Column(name = "nombre", length = 200)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @XmlTransient
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "subActividadEconomica")
    public Set<Cliente> getClientes() {
        return this.clientes;
    }

    public void setClientes(Set<Cliente> clientes) {
        this.clientes = clientes;
    }

}
