package co.edu.uniautonoma.sioat.datos;
// Generated 6/03/2018 01:23:43 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SubcuentaActivo generated by hbm2java
 */
@Entity
@Table(name = "subcuenta_activo")
public class SubcuentaActivo implements java.io.Serializable {

    private SubcuentaActivoId id;
    private Activo activo;
    private Subcuenta subcuenta;
    private Date fechaRegistro;

    public SubcuentaActivo() {
    }

    public SubcuentaActivo(SubcuentaActivoId id, Activo activo, Subcuenta subcuenta) {
        this.id = id;
        this.activo = activo;
        this.subcuenta = subcuenta;
    }

    public SubcuentaActivo(SubcuentaActivoId id, Activo activo, Subcuenta subcuenta, Date fechaRegistro) {
        this.id = id;
        this.activo = activo;
        this.subcuenta = subcuenta;
        this.fechaRegistro = fechaRegistro;
    }

    @EmbeddedId

    @AttributeOverrides({
        @AttributeOverride(name = "idActivo", column = @Column(name = "id_activo", nullable = false))
        , 
        @AttributeOverride(name = "idSubcuenta", column = @Column(name = "id_subcuenta", nullable = false))})
    public SubcuentaActivoId getId() {
        return this.id;
    }

    public void setId(SubcuentaActivoId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_activo", nullable = false, insertable = false, updatable = false)
    public Activo getActivo() {
        return this.activo;
    }

    public void setActivo(Activo activo) {
        this.activo = activo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_subcuenta", nullable = false, insertable = false, updatable = false)
    public Subcuenta getSubcuenta() {
        return this.subcuenta;
    }

    public void setSubcuenta(Subcuenta subcuenta) {
        this.subcuenta = subcuenta;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_registro", length = 19)
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }

    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

}
