package co.edu.uniautonoma.sioat.datos;
// Generated 6/03/2018 01:23:43 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SubcuentaCosto generated by hbm2java
 */
@Entity
@Table(name = "subcuenta_costo")
public class SubcuentaCosto implements java.io.Serializable {

    private SubcuentaCostoId id;
    private Costo costo;
    private Subcuenta subcuenta;
    private Date fechaRegistro;

    public SubcuentaCosto() {
    }

    public SubcuentaCosto(SubcuentaCostoId id, Costo costo, Subcuenta subcuenta) {
        this.id = id;
        this.costo = costo;
        this.subcuenta = subcuenta;
    }

    public SubcuentaCosto(SubcuentaCostoId id, Costo costo, Subcuenta subcuenta, Date fechaRegistro) {
        this.id = id;
        this.costo = costo;
        this.subcuenta = subcuenta;
        this.fechaRegistro = fechaRegistro;
    }

    @EmbeddedId

    @AttributeOverrides({
        @AttributeOverride(name = "idSubcuenta", column = @Column(name = "id_subcuenta", nullable = false))
        , 
        @AttributeOverride(name = "idCosto", column = @Column(name = "id_costo", nullable = false))})
    public SubcuentaCostoId getId() {
        return this.id;
    }

    public void setId(SubcuentaCostoId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_costo", nullable = false, insertable = false, updatable = false)
    public Costo getCosto() {
        return this.costo;
    }

    public void setCosto(Costo costo) {
        this.costo = costo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_subcuenta", nullable = false, insertable = false, updatable = false)
    public Subcuenta getSubcuenta() {
        return this.subcuenta;
    }

    public void setSubcuenta(Subcuenta subcuenta) {
        this.subcuenta = subcuenta;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_registro", length = 19)
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }

    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

}
