package co.edu.uniautonoma.sioat.datos;
// Generated 6/03/2018 01:23:43 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SubcuentaPasivo generated by hbm2java
 */
@Entity
@Table(name = "subcuenta_pasivo")
public class SubcuentaPasivo implements java.io.Serializable {

    private SubcuentaPasivoId id;
    private Pasivo pasivo;
    private Subcuenta subcuenta;
    private Date fechaRegistro;

    public SubcuentaPasivo() {
    }

    public SubcuentaPasivo(SubcuentaPasivoId id, Pasivo pasivo, Subcuenta subcuenta) {
        this.id = id;
        this.pasivo = pasivo;
        this.subcuenta = subcuenta;
    }

    public SubcuentaPasivo(SubcuentaPasivoId id, Pasivo pasivo, Subcuenta subcuenta, Date fechaRegistro) {
        this.id = id;
        this.pasivo = pasivo;
        this.subcuenta = subcuenta;
        this.fechaRegistro = fechaRegistro;
    }

    @EmbeddedId

    @AttributeOverrides({
        @AttributeOverride(name = "idSubcuenta", column = @Column(name = "id_subcuenta", nullable = false))
        , 
        @AttributeOverride(name = "idPasivo", column = @Column(name = "id_pasivo", nullable = false))})
    public SubcuentaPasivoId getId() {
        return this.id;
    }

    public void setId(SubcuentaPasivoId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_pasivo", nullable = false, insertable = false, updatable = false)
    public Pasivo getPasivo() {
        return this.pasivo;
    }

    public void setPasivo(Pasivo pasivo) {
        this.pasivo = pasivo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_subcuenta", nullable = false, insertable = false, updatable = false)
    public Subcuenta getSubcuenta() {
        return this.subcuenta;
    }

    public void setSubcuenta(Subcuenta subcuenta) {
        this.subcuenta = subcuenta;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_registro", length = 19)
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }

    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

}
