package co.edu.uniautonoma.sioat.datos;
// Generated 6/03/2018 01:23:43 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Subcuenta generated by hbm2java
 */
@Entity
@Table(name = "subcuenta")
public class Subcuenta implements java.io.Serializable {

    private Integer id;
    private Cifra cifra;
    private Renta renta;
    private Subcuenta subcuenta;
    private String nombre;
    private String codigo;
    private String tipo;
    private Set<Subcuenta> subcuentas = new HashSet<Subcuenta>(0);
    private Set<SubcuentaCosto> subcuentaCostos = new HashSet<SubcuentaCosto>(0);
    private Set<SubcuentaActivo> subcuentaActivos = new HashSet<SubcuentaActivo>(0);
    private Set<SubcuentaPasivo> subcuentaPasivos = new HashSet<SubcuentaPasivo>(0);
    private Set<SubcuentaIngreso> subcuentaIngresos = new HashSet<SubcuentaIngreso>(0);

    public Subcuenta() {
    }

    public Subcuenta(String nombre, String codigo, String tipo) {
        this.nombre = nombre;
        this.codigo = codigo;
        this.tipo = tipo;
    }

    public Subcuenta(Cifra cifra, Renta renta, Subcuenta subcuenta, String nombre, String codigo, String tipo, Set<Subcuenta> subcuentas, Set<SubcuentaCosto> subcuentaCostos, Set<SubcuentaActivo> subcuentaActivos, Set<SubcuentaPasivo> subcuentaPasivos, Set<SubcuentaIngreso> subcuentaIngresos) {
        this.cifra = cifra;
        this.renta = renta;
        this.subcuenta = subcuenta;
        this.nombre = nombre;
        this.codigo = codigo;
        this.tipo = tipo;
        this.subcuentas = subcuentas;
        this.subcuentaCostos = subcuentaCostos;
        this.subcuentaActivos = subcuentaActivos;
        this.subcuentaPasivos = subcuentaPasivos;
        this.subcuentaIngresos = subcuentaIngresos;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_cifra")
    public Cifra getCifra() {
        return this.cifra;
    }

    public void setCifra(Cifra cifra) {
        this.cifra = cifra;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_renta")
    public Renta getRenta() {
        return this.renta;
    }

    public void setRenta(Renta renta) {
        this.renta = renta;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_padre")
    public Subcuenta getSubcuenta() {
        return this.subcuenta;
    }

    public void setSubcuenta(Subcuenta subcuenta) {
        this.subcuenta = subcuenta;
    }

    @Column(name = "nombre", nullable = false, length = 50)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "codigo", nullable = false, length = 6)
    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    @Column(name = "tipo", nullable = false, length = 15)
    public String getTipo() {
        return this.tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    @XmlTransient
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "subcuenta")
    public Set<Subcuenta> getSubcuentas() {
        return this.subcuentas;
    }

    public void setSubcuentas(Set<Subcuenta> subcuentas) {
        this.subcuentas = subcuentas;
    }

    @XmlTransient
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "subcuenta")
    public Set<SubcuentaCosto> getSubcuentaCostos() {
        return this.subcuentaCostos;
    }

    public void setSubcuentaCostos(Set<SubcuentaCosto> subcuentaCostos) {
        this.subcuentaCostos = subcuentaCostos;
    }

    @XmlTransient
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "subcuenta")
    public Set<SubcuentaActivo> getSubcuentaActivos() {
        return this.subcuentaActivos;
    }

    public void setSubcuentaActivos(Set<SubcuentaActivo> subcuentaActivos) {
        this.subcuentaActivos = subcuentaActivos;
    }

    @XmlTransient
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "subcuenta")
    public Set<SubcuentaPasivo> getSubcuentaPasivos() {
        return this.subcuentaPasivos;
    }

    public void setSubcuentaPasivos(Set<SubcuentaPasivo> subcuentaPasivos) {
        this.subcuentaPasivos = subcuentaPasivos;
    }

    @XmlTransient
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "subcuenta")
    public Set<SubcuentaIngreso> getSubcuentaIngresos() {
        return this.subcuentaIngresos;
    }

    public void setSubcuentaIngresos(Set<SubcuentaIngreso> subcuentaIngresos) {
        this.subcuentaIngresos = subcuentaIngresos;
    }

}
