package co.edu.uniautonoma.sioat.datos;
// Generated 6/03/2018 01:23:43 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SubcuentaIngreso generated by hbm2java
 */
@Entity
@Table(name = "subcuenta_ingreso")
public class SubcuentaIngreso implements java.io.Serializable {

    private SubcuentaIngresoId id;
    private Ingreso ingreso;
    private Subcuenta subcuenta;
    private Date fechaRegistro;

    public SubcuentaIngreso() {
    }

    public SubcuentaIngreso(SubcuentaIngresoId id, Ingreso ingreso, Subcuenta subcuenta) {
        this.id = id;
        this.ingreso = ingreso;
        this.subcuenta = subcuenta;
    }

    public SubcuentaIngreso(SubcuentaIngresoId id, Ingreso ingreso, Subcuenta subcuenta, Date fechaRegistro) {
        this.id = id;
        this.ingreso = ingreso;
        this.subcuenta = subcuenta;
        this.fechaRegistro = fechaRegistro;
    }

    @EmbeddedId

    @AttributeOverrides({
        @AttributeOverride(name = "idSubcuenta", column = @Column(name = "id_subcuenta", nullable = false))
        , 
        @AttributeOverride(name = "idIngreso", column = @Column(name = "id_ingreso", nullable = false))})
    public SubcuentaIngresoId getId() {
        return this.id;
    }

    public void setId(SubcuentaIngresoId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_ingreso", nullable = false, insertable = false, updatable = false)
    public Ingreso getIngreso() {
        return this.ingreso;
    }

    public void setIngreso(Ingreso ingreso) {
        this.ingreso = ingreso;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_subcuenta", nullable = false, insertable = false, updatable = false)
    public Subcuenta getSubcuenta() {
        return this.subcuenta;
    }

    public void setSubcuenta(Subcuenta subcuenta) {
        this.subcuenta = subcuenta;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_registro", length = 19)
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }

    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

}
