package co.edu.uniautonoma.sioat.datos;
// Generated 6/03/2018 01:23:43 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SubcuentaCostoId generated by hbm2java
 */
@Embeddable
public class SubcuentaCostoId implements java.io.Serializable {

    private int idSubcuenta;
    private int idCosto;

    public SubcuentaCostoId() {
    }

    public SubcuentaCostoId(int idSubcuenta, int idCosto) {
        this.idSubcuenta = idSubcuenta;
        this.idCosto = idCosto;
    }

    @Column(name = "id_subcuenta", nullable = false)
    public int getIdSubcuenta() {
        return this.idSubcuenta;
    }

    public void setIdSubcuenta(int idSubcuenta) {
        this.idSubcuenta = idSubcuenta;
    }

    @Column(name = "id_costo", nullable = false)
    public int getIdCosto() {
        return this.idCosto;
    }

    public void setIdCosto(int idCosto) {
        this.idCosto = idCosto;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof SubcuentaCostoId)) {
            return false;
        }
        SubcuentaCostoId castOther = (SubcuentaCostoId) other;

        return (this.getIdSubcuenta() == castOther.getIdSubcuenta())
                && (this.getIdCosto() == castOther.getIdCosto());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getIdSubcuenta();
        result = 37 * result + this.getIdCosto();
        return result;
    }

}
